### ISSUE TITLE
应该把原 repo 的主分支一起 push 上来

### ISSUE THREAD

**Issue by nightire** [justjavac/json-api-zh_CN#2]
现在原 repo 的主分支是 1.0，应该把这个分支也 push 上来，否则没有用于本地开发的源代码文件。只推 gh-pages 就只有 build 之后的文件，fork 过来怎么 bundle？怎么 rake？

麻烦您把原 repo 的主干也一起提上来吧，我就不 PR 了，因为我只能 pull 到纯英文的，会覆盖已经翻译好的部分，谢谢。

**Comment by justjavac** [comment]
gh-pages-en 是原始的英文 branch

**Comment by nightire** [comment]
嗯，我知道。

可是这个不是这么玩的，应该用主干分支，然后可以直接在本地运行起来，一边翻译一边就可以看到真实的结果，之后再 build 得到 gh-pages 的结果。

即使只有 gh-pages 也罢，但是 Gemfile 和 Rakefile 在这个 fork 里都没有提交上来，没办法在本地预览和构建。

**Comment by huang-xiao-jian** [comment]
如果只是翻译的话，包缺失并不影响，注明应该就行。

**Comment by nightire** [comment]
@bornkiller 我的意思不是影响与否，而是翻译起来不方便，没有本地服务器支持预览的话，翻译的效果不能实时看到。如果只是纯文本来写作的话，原 repo 也没必要弄个 jekyll 来了。

**Comment by huang-xiao-jian** [comment]
我按照https://help.github.com/articles/using-jekyll-with-pages/  介绍`install jekyll`章节处理，现在可以实现本地预览。

**Comment by nightire** [comment]
@bornkiller 看一下 https://github.com/json-api/json-api/tree/1.0

这是 upstream repo 的主干分支，对比一下缺少的文件——**你根本就不需要手动搭建本地预览的环境，你所需要的只是 `bundle && bundle exec rake preview:browser`**——这也正是 README 最后所描述的内容。

也就是说：如果这个 repo 应该不只是 forking _gh-pages_ 这个分支，同时也应该把 upstream repo 的 `1.0` 分支也一起 forking 上来，这样其他的协作者就不需要考虑**如何本地预览**的问题。

That is how it suppose to be: automation, not manually.
